### 클라이언트 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

### 프리랜서 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "freelancer@test.com",
  "password": "1234"
}

### 프리랜서 리뷰 작성
POST http://localhost:8080/api/reviews/freelancers
Authorization: Bearer {{client_jwt}}
Content-Type: application/json

{
  "projectId": 1,
  "freelancerId": 2,
  "workQuality": 4.5,
  "deadline": 4.0,
  "communication": 5.0,
  "expertise": 4.5,
  "comment": "소통이 좋고 작업 퀄리티가 높았습니다."
}

### 프리랜서 리뷰 목록 조회
GET http://localhost:8080/api/reviews/freelancers/2

### 클라이언트 리뷰 작성
POST http://localhost:8080/api/reviews/clients
Authorization: Bearer 프리랜서_토큰_여기붙이기
Content-Type: application/json

{
  "projectId": 1,
  "clientId": 1,
  "requirementClarity": 4.0,
  "communication": 4.5,
  "paymentReliability": 5.0,
  "workAttitude": 4.5,
  "comment": "요구사항이 명확하고 협업이 수월했습니다."
}

### 클라이언트 리뷰 목록 조회
GET http://localhost:8080/api/reviews/clients/1